org.gradle.jvmargs=-Xmx1024M -XX:MaxMetaspaceSize=256m -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Program Files/Android/openjdk/jdk-21.0.8
android.useAndroidX=true
android.builder.sdkDownload=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false
org.gradle.daemon=false
org.gradle.parallel=false
