// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM-OdUQXyG4OFjK8_r7_8fekr9iPktSWg',
    appId: '1:634936246548:web:560013ce1d57aa19504201',
    messagingSenderId: '634936246548',
    projectId: 'memento-2927a',
    authDomain: 'memento-2927a.firebaseapp.com',
    storageBucket: 'memento-2927a.firebasestorage.app',
    measurementId: 'G-706M8DHK5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9N63zI6w3G6VBPq6oGc2WHvCB_3Jf4c',
    appId: '1:634936246548:android:02c393dc8081ef91504201',
    messagingSenderId: '634936246548',
    projectId: 'memento-2927a',
    storageBucket: 'memento-2927a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdqiGatJzStbuyVvpELsmIHx_pU2YT4bg',
    appId: '1:634936246548:ios:988380387f378ee5504201',
    messagingSenderId: '634936246548',
    projectId: 'memento-2927a',
    storageBucket: 'memento-2927a.firebasestorage.app',
    iosBundleId: 'com.memento.memento',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdqiGatJzStbuyVvpELsmIHx_pU2YT4bg',
    appId: '1:634936246548:ios:988380387f378ee5504201',
    messagingSenderId: '634936246548',
    projectId: 'memento-2927a',
    storageBucket: 'memento-2927a.firebasestorage.app',
    iosBundleId: 'com.memento.memento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM-OdUQXyG4OFjK8_r7_8fekr9iPktSWg',
    appId: '1:634936246548:web:f2163d9dc876b606504201',
    messagingSenderId: '634936246548',
    projectId: 'memento-2927a',
    authDomain: 'memento-2927a.firebaseapp.com',
    storageBucket: 'memento-2927a.firebasestorage.app',
    measurementId: 'G-9Y2GTELNH7',
  );
}
